Update final-workflow-csv.yml with commenting list env's

diff --git a/.github/workflows/final-workflow-csv.yml b/.github/workflows/final-workflow-csv.yml
--- a/.github/workflows/final-workflow-csv.yml
+++ b/.github/workflows/final-workflow-csv.yml
@@ -1,4 +1,4 @@
-name: Add Environment Variables (YS latest)
+name: Add Environment Variables (YS)
 
 on:
   workflow_dispatch:
@@ -40,11 +40,10 @@ jobs:
 
     - name: Add Environment Variables to Repositories
       env:
-        GITFLOW_GITHUB_TOKEN: ${{ secrets.GITFLOW_GITHUB_TOKEN }}
+        GITFLOW_GITHUB_TOKEN: ${{ secrets.TOKEN }}
         ENV_NAME: ${{ github.event.inputs.actual_env_name }}
         VAR_NAME: ${{ github.event.inputs.var_name }}
         VAR_VALUE: ${{ github.event.inputs.env_name }}
-        REPOS: ${{ env.repos }}
 
       run: |
         repos="${{ steps.read-repos.outputs.repos }}"
@@ -54,7 +53,7 @@ jobs:
 
           # Fetch existing environments to check if the environment exists
           echo "Fetching environments for repository: $repo"
-          response=$(curl -H "Authorization: token $GITFLOW_GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" \
+          response=$(curl -s -H "Authorization: token $GITFLOW_GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository_owner }}/$repo/environments)
           
           echo "Response: $response"
@@ -63,20 +62,52 @@ jobs:
             echo "Failed to fetch environments for $repo"
             continue
           fi
+
+          # List environments
+          #echo "Environments in $repo: $(echo $response | jq -r '.environments[].name')"
           
           # Check if environment exists
-          env_id=$(echo $response | jq -r --arg ENV_NAME "$ENV_NAME" '.environments[]? | select(.name == $ENV_NAME) | .id')
+          env_id=$(echo "$response" | jq -r --arg ENV_NAME "$ENV_NAME" '.environments[]? | select(.name == $ENV_NAME) | .id')
           
           if [ -z "$env_id" ]; then
             echo "Creating environment: $ENV_NAME"
-            create_env_response=$(curl -X PUT -H "Authorization: token $GITFLOW_GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" \
-              https://api.github.com/repos/${{ github.repository_owner }}/$repo/environments/$ENV_NAME)
+            create_env_response=$(curl -s -X POST -H "Authorization: token $GITFLOW_GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/${{ github.repository_owner }}/$repo/environments -d "{\"name\":\"$ENV_NAME\"}")
+            if [ $? -ne 0 ]; then
+              echo "Failed to create environment $ENV_NAME for $repo"
+              echo "Create Environment Response: $create_env_response"
+              continue
+            fi
+            env_id=$(echo "$create_env_response" | jq -r '.id')
           else
-             echo "Environment $ENV_NAME already exists"
+            echo "Environment $ENV_NAME already exists"
           fi
           
-          # Add the environment variable
-          echo "Adding environment variable: $VAR_NAME with value $VAR_VALUE"
-          curl -X POST -H "Authorization: token $GITFLOW_GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository_owner }}/$repo/environments/$ENV_NAME/variables \
-            -d "{\"name\":\"$VAR_NAME\", \"value\":\"$VAR_VALUE\"}"
+          # Fetch environment variables
+          env_vars_response=$(curl -s -H "Authorization: token $GITFLOW_GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/${{ github.repository_owner }}/$repo/environments/$ENV_NAME/variables)
+          
+          echo "Environment Variables Response: $env_vars_response"
+          
+          if [ $? -ne 0 ]; then
+            echo "Failed to fetch environment variables for $ENV_NAME in $repo"
+            continue
+          fi
+
+          # Check if environment variable exists
+          var_exists=$(echo "$env_vars_response" | jq -r --arg VAR_NAME "$VAR_NAME" --arg VAR_VALUE "$VAR_VALUE" '.variables[]? | select(.name == $VAR_NAME and .value == $VAR_VALUE) | .name')
+          
+          if [ -n "$var_exists" ]; then
+            echo "Environment variable $VAR_NAME with value $VAR_VALUE already exists in $ENV_NAME for $repo"
+          else
+            echo "Adding environment variable: $VAR_NAME with value $VAR_VALUE"
+            add_var_response=$(curl -s -X POST -H "Authorization: token $GITFLOW_GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" \
+                https://api.github.com/repos/${{ github.repository_owner }}/$repo/environments/$ENV_NAME/variables \
+                -d "{\"name\":\"$VAR_NAME\", \"value\":\"$VAR_VALUE\"}")
+            if [ $? -ne 0 ]; then
+              echo "Failed to add environment variable $VAR_NAME for $repo"
+              echo "Add Variable Response: $add_var_response"
+              continue
+            fi
+          fi
         done
